* Jujutsu Workflow Walkthroughs
** Installation and Setup
Install jujutsu with Homebrew.

#+begin_src fish
brew install jujutsu
#+end_src

Configure basic user information with the ~config~ command. The config command has
two sub-commands, ~set~ and ~get~, that do what the name implies. Configuration
values can be set for a specific repository with the ~--repo~ switch, or for the
current user with the ~--user~ switch.

Let's set the user name and email globally for the current user.

#+begin_src fish
jj config set --user user.name "Christian Romney"
jj config set --user user.email "christian.romney@nubank.com.br"
#+end_src

You can also specify a command to run when ~jj~ is invoked with no arguments. By
default, this is the ~log~ command, but you can change this configuration if you
prefer something else.

#+begin_src fish
jj config set --repo ui.default-command status
#+end_src

Now typing only ~jj~ will show the equivalent of ~jj status~ instead when working in
this repository.

Through configuration you can control how jj displays information as well as its
behavior during certain operations. Besides simple values, jj also has a
[[https://jj-vcs.github.io/jj/latest/templates/][templating language]] which can be used to set default commit messages and format
output. Consult the [[https://jj-vcs.github.io/jj/latest/config/][configuration documentation]] for the full set of options.

** Starting New Work
*** Initialization
Before we can use jujutsu to version work, we must initialize a repository. If
you do not plan to use Git commands locally and are working with a brand new jj
repository, you can use the following command:

#+begin_src fish
jj git init
#+end_src

This will create a ~.jj~ directory which holds the respository and configuration
files. There will be no ~.git~ directory in the repository root. If you plan to
invoke ~git~ commands or are working with an existing repo, then you should use
this command instead:

#+begin_src fish
jj git init --colocate
#+end_src

This will keep both a ~.git~ and ~.jj~ directory as siblings in the root. Let's
ensure Git ignores jujutsu folders, since jj knows about git but not the other
way around.

#+begin_src fish
echo ".jj" >> $HOME/.gitignore_global
#+end_src

Jujutsu was designed to support different backends to perform lower level
storage operations. The ~git~ backend is currently the only production-ready
implementation.

View the status of your repository with the ~status~ command.

#+begin_src fish
jj status
#+end_src

Your working copy (~@~) should have no changes nor any description set. You should
see one parent (~@-~) commit which is the empty commit whose commit hash
is 00000000. Each jujutsu commit is associated with a commit hash based on its
content (like Git) as well as a change id which is a stable name for a logical
change. This change id immediately precedes the commit hash.

**** Changes, Commits, and the Working Copy
One way to think of the difference between a Change and a commit is that a
Change represents a desired unit of alteration. It's your complete set of
intended modifications. Commits, on the other hand, are the low-level mechanical
increments we take to effect a change. Many commits are created passively.
Unlike git, where the user must signal a specific intent to memorialize
modifications, jujutsu creates commits as side-effects to most ~jj~ commands.

Even viewing the status of the repository will create a new commit /if there are
alterations in the state of the Working Copy/. Jujutsu does this to eliminate the
need to think about staging work regularly. All pending work is automatically
committed on every jujutsu command. This allows the developer to recover any
prior state easily (via ~undo~ and ~redo~), at the small expense of more commits.

As one might expect, jujutsu also provides tools to keep a change's history tidy.
*** Versioning Work
Start new work by creating a new Change with the ~new~ command.

#+begin_src fish
jj new
#+end_src

It's good practice to ~describe~ the work with a message.

#+begin_src fish
jj describe -m "Add README documentation"
#+end_src

Because it's so common to perform both of these actions in succession, the new
command supports adding a description in one step.

#+begin_src fish
jj new -m "Add README documentation"
#+end_src

You will notice the new commit has a new change id. The minimum number of
characters needed to identify a change id are highlighted. As ~new~ changes branch
off prior ones, additional characters may be appended. Notice how the commit
hash of the parent of the working copy (~@-~) is the same as the initial working
copy hash when the repository was created.

The ~log~ command displays this history neatly.

#+begin_src fish
jj log
#+end_src

We first see the current change which has a description but no content. Next, we
see the parent which represented the new, empty repository. Finally we have the
empty, root commit. Let's describe the initial state.

#+begin_src fish
jj describe -m "Initial empty repository" @-
#+end_src

The last argument to the ~describe~ command is a /REVSET/, which identifies a point
in the project's history. In this case, we use the shorthand ~@-~ which identifies
the parent (-) of the working copy (@). We can back up generations by appending
more (-) signs, so that ~@--~ is the grandparent. View the log to see the new
description reflected in the history.

Since we plan to make a series of modifications, it's a good idea to create a
new ~bookmark~ for this work. A bookmark is nothing more than a user-assigned
label for a commit. It is analogous to a branch in Git. jujutsu uses different
names for its commands when the concept has important differences from its Git
counterpart. Later we will show how jujutsu and Git interoperate.

#+begin_src fish
jj bookmark create -r@ docs
#+end_src

The status command shows the new bookmark after the commit hash.

Make some changes to ~README.md~ then run ~jj~. You can see that the working copy
changes are added automatically. Execute the ~diff~ command to view the details.

#+begin_src fish
jj diff
#+end_src

** Workflows
There are two popular alternative workflows for jujutsu: the squash and edit
workflows.
*** Squash Workflow
**** Create the parent (target)
First create a new change and describe it.

#+begin_src fish
jj new
jj describe -m "Add some feature"
#+end_src

This change is empty, but has a description. It will be the logical target of
our curated changes.

**** Create the working copy (staging area)

Next, create a new empty change for our working copy.

#+begin_src fish
jj new
# ... add/remove/modify files ...
#+end_src

Begin modifying files. Build changes up in the working copy until you've
satisfied what you described in the first step.

**** Squash Changes

Finally, squash those changes to push them down to described change.

#+begin_src fish
jj squash # everything, or...
jj squash path/to/file # just certain files, or...
jj squash -i # interactively squash certain "hunks"
#+end_src

The interactive version of the command allows for more fine-grained control even
within a single file.

*** Edit Workflow
**** Rewriting Ancestry
In this workflow, we edit the change we want to commit to anywhere in the
history. One way to do this is to add new commits in the /past/.

#+begin_src fish
jj new -B @ -m "Pretend we did this earlier"
#+end_src

The ~-B~ flag means /before/ the named change. The output of this command shows
"Rebased 1 descendant commits," because the working copy must be a child of the
newly inserted change. You'll notice the working copy ~@~ is now at that commit.

Any modifications we make at this point are to the earlier (but current) change
and will trigger further rebases.

**** Editing Arbitrary Changes
When we're ready to go back to the future, we can either ~edit~ the change with
the right change/commit id or use the ~next~ command.

#+begin_src fish
jj next --edit
#+end_src

Next moves the working copy to the child of the current change. We must supply
the ~--edit~ argument to edit the pre-existing change. Otherwise, next will create
a ~new~ change which would be a sibling to the prior child.

*** Miscellaneous Commands
- abandon : to throw things away from the WC
- split : to interactively create multiple changes from WC

** The Revset Language
Revsets are a functional language for specifying a range of commits. Most
commands support a ~-r~ parameter for specifying revsets.
*** Symbols
- @ :: the working copy

*** Operators
- x & y :: changes in both x and y
- x | y :: changes in either x or y
- ::x :: ancestors of x
- x:: :: descendants of x

*** Functions
- root() :: the root commit of the repository
- all() :: all /visible/ changes
- mine() :: all changes authored by the current user
- parents(x) :: parents of change x
- ancestors(x, [limit]) :: ancestors of x, optionally with a limit
- heads(x) :: commits in x that are not parents of other commits (leaves)
- description(x) :: commits that have x in the description

Consult the full revset language documentation.
** Bookmarks and Remote Git Repositories
We'll use Github to demonstrate interop with a remote Git repository.

#+begin_src fish
jj git remote add origin git@github.com:christianromney/jujutsu-notes.git
#+end_src

Git workflows are branch-oriented. In jujutsu, a branch is called a bookmark and
is merely a label pointing at a change. The primary difference between a
bookmark name and a change id is that a developer chooses the former and jujutsu
chooses the latter.

Bookmarks have some other capabilities as well, but this simplified mental model
de-mystifies them.

Let's create a new bookmark at the working copy and push it to the origin.

#+begin_src fish
jj bookmark create main -r @
jj git push --bookmark main --remote origin
#+end_src

Since the bookmark is now part of an externally visible Git branch, jujutsu
marks the change where the bookmark is pointing as immutable. This prevents
breaking history for others. A new, empty, undescribed commit is also created
for the working copy.

We can make further edits, and they will all be part of the working copy. Once
we're ready to send them upstream, we can move the bookmark to our new commit
and push the bookmark.

#+begin_src fish
jj bookmark move main --to @
jj git push
#+end_src

Once again, a new commit is created after the push to hold any new changes. If
we tried to squash the commit into the parent, the operation would fail since
shared history is protected by making it immutable.

** Rebasing
Just as we can push commits from a remote repository, we can also fetch them.
Make a change in the browser on Github, and commit it directly to the main
branch. Create some local changes, and be sure to describe them. Then, fetch the
remote changes.

#+begin_src fish
jj git fetch
#+end_src

This produces the following repository state:

#+begin_example
@  wurtosxt christian.a.romney@gmail.com 2025-09-04 14:38:27 24c384bd
│  Describe rebasing local work on remote changes
│ ◆  zrpoqnvk christian.romney@nubank.com.br 2025-09-04 14:35:36 main c5fdfaeb
├─╯  Add link to jujutsu GitHub repository
◆  syrylumy christian.a.romney@gmail.com 2025-09-04 13:47:30 d5a65b2b
│  Complete bookmark push description
~
#+end_example

Note that ~main~ and the working copy (~@~) have diverged from their common
branching point. Since I've only just started working on this section, I want to
rebase my current working copy on main to get a linear history.

#+begin_src fish
jj rebase --destination main

Rebased 1 commits to destination
Working copy  (@) now at: wurtosxt 7cfd0faf Describe rebasing local work on remote changes
Parent commit (@-)      : zrpoqnvk c5fdfaeb main | Add link to jujutsu GitHub repository
Added 0 files, modified 1 files, removed 0 files
#+end_src

Let's look at the re-written history with ~jj log~:

#+begin_example
@  wurtosxt christian.a.romney@gmail.com 2025-09-04 14:46:46 9f6e91dd
│  Describe rebasing local work on remote changes
◆  zrpoqnvk christian.romney@nubank.com.br 2025-09-04 14:35:36 main c5fdfaeb
│  Add link to jujutsu GitHub repository
~
#+end_example

Note: The log command will truncate its output by default. Use ~--revisions~ flag
in combination with the revset language to view as much of the history as you like:

#+begin_src fish
jj log --revisions 'all()'
#+end_src

For example, the ~all()~ function shows the complete history.

#+begin_example
@  wurtosxt christian.a.romney@gmail.com 2025-09-04 14:49:42 3600f4d3
│  Describe rebasing local work on remote changes
◆  zrpoqnvk christian.romney@nubank.com.br 2025-09-04 14:35:36 main c5fdfaeb
│  Add link to jujutsu GitHub repository
◆  syrylumy christian.a.romney@gmail.com 2025-09-04 13:47:30 d5a65b2b
│  Complete bookmark push description
◆  torpzozy christian.a.romney@gmail.com 2025-09-04 13:43:52 ec562ebe
│  Detail the Git bookmark interop
◆  prwmsnlq christian.a.romney@gmail.com 2025-09-04 13:29:36 add2f2e8
│  Add Git remote workflow
◆    rvkxmous christian.a.romney@gmail.com 2025-09-03 08:56:28 2430aa64
├─╮  Add configuration and merge initial tutorial
│ ◆  vnvnxusv christian.a.romney@gmail.com 2025-08-25 21:01:54 4b9f0212
│ │  Revsets
│ ◆  pywypnsl christian.a.romney@gmail.com 2025-08-25 20:57:40 be1d2e6d
│ │  Branching and Merging
│ ◆  swkupsqt christian.a.romney@gmail.com 2025-08-25 20:57:40 aeb38a0b
│ │  Detail the edit workflow
│ ◆  myvnwvrs christian.a.romney@gmail.com 2025-08-25 20:57:40 c242f7d0
│ │  Detail the squash workflow
│ ◆  xypktrzv christian.a.romney@gmail.com 2025-08-25 20:57:40 9b18a828
│ │  Document workflows
◆ │  yunzvmww christian.a.romney@gmail.com 2025-08-25 20:57:40 ca6c96d1
├─╯  Add cheatsheet
◆  trysnlpq christian.a.romney@gmail.com 2025-08-25 20:57:40 b9c04038
│  Add initial version generated by Claude
◆  zzzzzzzz root() 00000000
#+end_example

The rebase command is very powerful. It can act on multiple lineages at once,
whether on a single commit or all of its descendants. Take time to read through
the ~rebase~ documentation (~jj rebase --help~).

** Branching and Merging
All ~jj~ workflows use anonymous branches by default (detached HEADs in Git
parlance). Since every change is in essence a branch, there's no need to name
branches to accomplish every day tasks. Similarly, merging is just creating a
~new~ change with two (or more) parents.

#+begin_src fish
jj new p1 p2 -m "The new change that merges p1 and p2"
#+end_src

The new command has a lot of power: it can insert arbitrary changes, including
merges, at any point in the history.

*** Merging
Let's branch off our parent commit to create a parallel development line
that is a sibling to our working copy.

#+begin_src fish
jj new @-
jj describe -m "Describe the absorb command" # something we'll do later
#+end_src

This has the side effect of editing that new sideline. This is analogous to the
Git command ~git checkout -b~. Here's the current branch state:

#+begin_example
@  nyzqxvsv christian.a.romney@gmail.com 2025-09-04 19:00:06 c195a561
│  (empty) Describe the absorb command
│ ○  runwmuks christian.a.romney@gmail.com 2025-09-04 19:05:47 370ebda8
├─╯  Describe merging remote repository commits
◆  wurtosxt christian.a.romney@gmail.com 2025-09-04 14:50:43 main 54f36fc9
│  Describe rebasing local work on remote changes
~
#+end_example

We can return to our prior line by editing it:

#+begin_src fish
jj edit runwmuks
#+end_src

The log confirms it.

#+begin_example
@  runwmuks christian.a.romney@gmail.com 2025-09-04 19:10:15 77d3dcdb
│  Describe merging remote repository commits
│ ○  nyzqxvsv christian.a.romney@gmail.com 2025-09-04 19:00:06 c195a561
├─╯  (empty) Describe the absorb command
◆  wurtosxt christian.a.romney@gmail.com 2025-09-04 14:50:43 main 54f36fc9
│  Describe rebasing local work on remote changes
~
#+end_example

Now we'll make another edit directly on Github which we'll merge into both
branches. First we'll need to fetch from origin.

#+begin_src fish
jj git fetch
#+end_src

The new state of the repository is shown below.

#+begin_example
@  runwmuks christian.a.romney@gmail.com 2025-09-04 19:30:04 3df228b4
│  Describe merging remote repository commits
│ ◆  tqppyslv christian.romney@nubank.com.br 2025-09-04 19:29:22 main 063bb9b1
├─╯  Add link to JJ Intro and Patterns
│ ○  nyzqxvsv christian.a.romney@gmail.com 2025-09-04 19:00:06 c195a561
├─╯  (empty) Describe the absorb command
◆  wurtosxt christian.a.romney@gmail.com 2025-09-04 14:50:43 54f36fc9
│  Describe rebasing local work on remote changes
~
#+end_example

We can merge the changes from main into the working copy by creating a new
commit that has both as parents.

#+begin_src fish
jj new runwmuks main
#+end_src

Notice we can mix change ids and bookmark names. We could also use a commit id
if we wanted; jj is flexible that way. The repository state now looks like this:

#+begin_example
@    wulwmvrz christian.a.romney@gmail.com 2025-09-04 19:33:26 aa60410e
├─╮  (empty) (no description set)
│ ◆  tqppyslv christian.romney@nubank.com.br 2025-09-04 19:29:22 main 063bb9b1
│ │  Add link to JJ Intro and Patterns
○ │  runwmuks christian.a.romney@gmail.com 2025-09-04 19:33:26 6d3e0457
├─╯  Describe merging remote repository commits
│ ○  nyzqxvsv christian.a.romney@gmail.com 2025-09-04 19:00:06 c195a561
├─╯  (empty) Describe the absorb command
◆  wurtosxt christian.a.romney@gmail.com 2025-09-04 14:50:43 54f36fc9
│  Describe rebasing local work on remote changes
~
#+end_example

Let's describe the latest change before merging the main line into the absorb
branch.

#+begin_src fish
jj describe -m "Continue describing merges"
#+end_src

Now we can create a new change with both the link and absorb lines merged:

#+begin_src fish
jj new tq ny -m "Merge intro and patterns into absorb"
#+end_src

** Conflict Resolution
Converging the changes from the 'merge' and 'absorb' branches produced a conflict.

#+begin_example
@    yzvzskrr christian.a.romney@gmail.com 2025-09-04 20:48:55 2b0ef271 conflict
├─╮  (empty) Converge all changes
│ ○    uqovzsov christian.a.romney@gmail.com 2025-09-04 20:37:21 a3b9a71c
│ ├─╮  Merge intro and patterns into absorb
│ │ ○  nyzqxvsv christian.a.romney@gmail.com 2025-09-04 20:09:04 fb5a3f7f
│ │ │  Describe the absorb command
○ │ │  wulwmvrz christian.a.romney@gmail.com 2025-09-04 20:36:11 f0e49f94
├─╮ │  Complete merge description
│ ◆ │  tqppyslv christian.romney@nubank.com.br 2025-09-04 19:29:22 main 063bb9b1
│ ├─╯  Add link to JJ Intro and Patterns
○ │  runwmuks christian.a.romney@gmail.com 2025-09-04 19:33:26 6d3e0457
├─╯  Describe merging remote repository commits
◆  wurtosxt christian.a.romney@gmail.com 2025-09-04 14:50:43 54f36fc9
│  Describe rebasing local work on remote changes
~
#+end_example

The interesting thing to note is that the ~new~ operation succeeded. Conflicts
don't abort operations or leave the repository in an odd state. Conflicts are
recorded as first-class information. They don't prevent additional changes from
being created, either.

However, whether or not you choose to resolve conflicts first or continue
editing, *always create a new change* on top of a conflict. Once you've resolved
the conflict, squash it down into the conflicting commit.

#+begin_src fish
jj new -n "Describe conflicts"
#+end_src

We can add more content and defer the resolution until we want to deal with it.
In this case, I've added new content and resolved the conflict in the working
copy.

#+begin_example
@  qtxzvnzl christian.a.romney@gmail.com 2025-09-05 08:29:07 362320ae
│  Describe conflicts
×    yzvzskrr christian.a.romney@gmail.com 2025-09-04 20:48:55 2b0ef271 conflict
├─╮  (empty) Converge all changes
│ ○    uqovzsov christian.a.romney@gmail.com 2025-09-04 20:37:21 a3b9a71c
│ ├─╮  Merge intro and patterns into absorb
│ │ ○  nyzqxvsv christian.a.romney@gmail.com 2025-09-04 20:09:04 fb5a3f7f
│ │ │  Describe the absorb command
○ │ │  wulwmvrz christian.a.romney@gmail.com 2025-09-04 20:36:11 f0e49f94
├─╮ │  Complete merge description
│ ◆ │  tqppyslv christian.romney@nubank.com.br 2025-09-04 19:29:22 main 063bb9b1
│ ├─╯  Add link to JJ Intro and Patterns
○ │  runwmuks christian.a.romney@gmail.com 2025-09-04 19:33:26 6d3e0457
├─╯  Describe merging remote repository commits
◆  wurtosxt christian.a.romney@gmail.com 2025-09-04 14:50:43 54f36fc9
│  Describe rebasing local work on remote changes
~
#+end_example

Let's interactively split the current change into two different changes. When
the diff tool loads, any changes we leave on the *right* will be spun out into a
subsequent commit. This makes intuitive sense in the West, where we read from
left to right. The stuff on the left will stay behind in the existing commit.
Invoke the split command like so:

#+begin_src fish
jj split --tool meld
#+end_src

Once you've chose what to split, jj will launch your ~$EDITOR~ twice to amend
the commit messages in historical order. Now your history will look something like:

#+begin_src fish
@  pswmtnwq christian.a.romney@gmail.com 2025-09-05 08:43:05 2d4803d7
│  Reorder content and fix headings
○  qtxzvnzl christian.a.romney@gmail.com 2025-09-05 08:37:41 40afcb43
│  Describe merge conflicts
×    yzvzskrr christian.a.romney@gmail.com 2025-09-04 20:48:55 2b0ef271 conflict
├─╮  (empty) Converge all changes
│ ○    uqovzsov christian.a.romney@gmail.com 2025-09-04 20:37:21 a3b9a71c
│ ├─╮  Merge intro and patterns into absorb
│ │ ○  nyzqxvsv christian.a.romney@gmail.com 2025-09-04 20:09:04 fb5a3f7f
│ │ │  Describe the absorb command
○ │ │  wulwmvrz christian.a.romney@gmail.com 2025-09-04 20:36:11 f0e49f94
├─╮ │  Complete merge description
│ ◆ │  tqppyslv christian.romney@nubank.com.br 2025-09-04 19:29:22 main 063bb9b1
│ ├─╯  Add link to JJ Intro and Patterns
○ │  runwmuks christian.a.romney@gmail.com 2025-09-04 19:33:26 6d3e0457
├─╯  Describe merging remote repository commits
◆  wurtosxt christian.a.romney@gmail.com 2025-09-04 14:50:43 54f36fc9
│  Describe rebasing local work on remote changes
~
#+end_src

We can inspect the ~qtxzvnzl~ commit to ensure it actually fixes the merge
conflict before squashing it down into the conflict commit to resolve it.

#+begin_example
Commit ID: 40afcb43bd7007ea52654f1818ba7ac8b72018e2
Change ID: qtxzvnzlqvxlwnwvkllpmkqyryylomso
Author   : Christian Romney <christian.a.romney@gmail.com> (2025-09-04 20:51:56)
Committer: Christian Romney <christian.a.romney@gmail.com> (2025-09-05 08:37:41)

    Describe merge conflicts

Resolved conflict in jj.org:
    ...
  23   23: #+end_src
#+end_example

Now let's squash that commit and resolve the conflict:

#+begin_src fish
jj squash -f qt -t yz --use-destination-message
#+end_src

The ~-f~ and ~-t~ switches stand for *from* and *into* respectively. The history now
shows the resolved conflict.

#+begin_example
@  pswmtnwq christian.a.romney@gmail.com 2025-09-05 08:49:48 0a2ad2b6
│  Reorder content and fix headings
○    yzvzskrr christian.a.romney@gmail.com 2025-09-05 08:47:58 7fcda544
├─╮  Converge all changes
│ ○    uqovzsov christian.a.romney@gmail.com 2025-09-04 20:37:21 a3b9a71c
│ ├─╮  Merge intro and patterns into absorb
│ │ ○  nyzqxvsv christian.a.romney@gmail.com 2025-09-04 20:09:04 fb5a3f7f
│ │ │  Describe the absorb command
○ │ │  wulwmvrz christian.a.romney@gmail.com 2025-09-04 20:36:11 f0e49f94
├─╮ │  Complete merge description
│ ◆ │  tqppyslv christian.romney@nubank.com.br 2025-09-04 19:29:22 main 063bb9b1
│ ├─╯  Add link to JJ Intro and Patterns
○ │  runwmuks christian.a.romney@gmail.com 2025-09-04 19:33:26 6d3e0457
├─╯  Describe merging remote repository commits
◆  wurtosxt christian.a.romney@gmail.com 2025-09-04 14:50:43 54f36fc9
│  Describe rebasing local work on remote changes
~
#+end_example

** The Magic of Absorption
jujutsu's ~absorb~ command simplifies the process of pushing integration branch
changes upstream into the appropriate parent if those changes are unambiguous.

** Resources
- [[https://jj-vcs.github.io/jj/latest/][jj documentation]]
- [[https://steveklabnik.github.io/jujutsu-tutorial/][Steve Klabnik's Tutorial]]
- [[https://jj-for-everyone.github.io/introduction.html][jujutsu for Everyone]]
- [[https://github.com/jj-vcs/jj][jujutsu Github]]
- [[https://kubamartin.com/posts/introduction-to-the-jujutsu-vcs/][JJ Intro and Patterns]]
- [[https://v5.chriskrycho.com/journal/jujutsu-megamerges-and-jj-absorb/][JJ Merges and Absorb]]
